import Head from 'next/head';
import { MdOutlineQrCodeScanner } from 'react-icons/md';
import SingleTransactionList from '../components/SingleTransactionList';


export default function Dashboard() {

  return (
    <div>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className="w-full h-screen max-w-sm mx-auto">

        <div className='flex items-center py-4'>
            <div className='flex items-center space-x-3'>
                <div className='w-8 h-8 bg-purple-600 rounded-full'></div>
                <p className='text-xs font-bold'>Hello, Maxwell</p>
            </div>

            <MdOutlineQrCodeScanner className="text-xl text-purple-600 ml-auto" />
        </div>

        <div className='flex items-center px-8 py-12 bg-purple-600 text-white rounded-2xl'>
            <div className='space-y-2'>
                <p className='text-xs'>Account Balance</p>
                <p className='text-4xl font-bold'>&#8358; {(1_300).toLocaleString()}</p>
            </div>
        </div>

        <div className='grid grid-cols-2 gap-4 py-4'>
            <div className='p-4 bg-[#18A47E] text-xs text-center text-white rounded-xl'>Fund Wallet</div>
            <div className='p-4 bg-purple-600 text-xs text-center text-white rounded-xl'>Pay Bills</div>
        </div>

        <div className='py-4'>
            <p className='text-xs font-bold pb-3'>Transactions</p>
            <div className='space-y-3'>
                
                <SingleTransactionList 
                    type="credit"
                    details="James Nwoko"
                    amount="5000"
                />
                <SingleTransactionList
                    details="James Nwoko"
                    amount="2000"
                />
                
                <div className='flex justify-center'>
                    <div className='inline-block mx-auto rounded-md text-white bg-purple-600 py-2 px-4 text-xs font-bold'>More Transactions</div>
                </div>
            </div>
        </div>

      </main>

    </div>
  )
}
