import Head from 'next/head';
import { useRouter } from 'next/router';
import { useState } from 'react';
import { usePaystackPayment } from 'react-paystack';


export default function Dashboard() {

  const router = useRouter();
  const [config, setConfig] = useState({
    reference: (new Date()).getTime().toString(),
    email: "chibykes@gmail.com",
    amount: 20000,
    publicKey: 'pk_test_1036b2692892ebe21cf87429183177c154984321',
  });

  const initializePayment = usePaystackPayment(config);


  const onSuccess = (data) => {
    let trx = JSON.parse(localStorage.getItem('transactions')) || [];
    let updatedTrx = JSON.stringify([...trx, { 
      reference: config.reference,
      type: 'credit',
      email: config.email,
      amount: Number(config.amount) / 100,
      details: 'Wallet funding',
      data
    }]);

    localStorage.setItem('transactions', updatedTrx);
    router.push(`/success?reference=${data.reference}`);
  };
  
  
  const onClose = () => {
    // implementation for  whatever you want to do when the Paystack dialog closed.
    console.log('closed')
  }

  return (
    <div>
      <Head>
        <title>Fund Wallet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className="w-full h-screen max-w-sm mx-auto p-4">

        <div className='py-4'>
            <p className='text-xs text-center font-bold pb-3'>Fund Wallet</p>

            <form onSubmit={(e) => {e.preventDefault(); initializePayment(onSuccess, onClose)}} className='pt-4 space-y-5'>

              <div className='bg-white border border-purple-600 rounded-md py-2 px-3'>
                <input
                  name="amount"
                  type="number"
                  className="text-xs border-none outline-none focus:ring-transparent block w-full"
                  placeholder="Amount"
                  onChange={(e) => setConfig({ ...config, [e.target.name]: e.target.value * 100 })}
                  required
                />
              </div>

              <button type='submit' className='w-full text-xs text-center font-bold text-white bg-purple-600 border-2 border-purple-600 rounded-md py-4 px-3'>
                  Fund
              </button>
                
            </form>
        </div>

      </main>

    </div>
  )
}
