import Head from 'next/head';
import { useEffect, useState } from 'react';
import { MdOutlineQrCodeScanner } from 'react-icons/md';
import SingleTransactionList from '../components/SingleTransactionList';


export default function Dashboard() {

  const [transactions, setTransctions] = useState([]);

  useEffect(() => {
    setTransctions(JSON.parse(localStorage.getItem('transactions')).reverse() || []);
  }, []);

  return (
    <div>
      <Head>
        <title>History</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className="w-full h-screen max-w-sm mx-auto">

        <div className='py-4'>
            <p className='text-xs text-center font-bold pb-3'>History</p>
            <div className='pt-4 space-y-3'>
                
              {transactions.map((trx, index) => (
                <SingleTransactionList 
                  key={index}
                  {...trx}
                />
              ))}
                
            </div>
        </div>

      </main>

    </div>
  )
}
