import Head from "next/head";
import Link from "next/link";
import { FcGoogle } from 'react-icons/fc'


export default function Login() {

    return(
        <>
            <div className="fixed w-full h-full bg-purple-600">
                <Head>
                    <title>Login</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <main className="max-w-sm mx-auto space-y-24 text-center py-24 px-4">
                    <p className="text-3xl font-bold text-white">NowPay</p>

                    <div className="space-y-8">
                        <p className="text-sm text-white">Sign in or Sign up</p>
                        <Link href="/dashboard" className="bg-white cursor-pointer rounded-full py-4 px-12 text-center flex justify-center items-center">
                            <FcGoogle className="" />
                            <span className="text-app-gray text-xs pl-2">Continue with Google</span>
                        </Link>
                    </div>
                </main>
            </div>
        
        </>
    );

}