import Head from 'next/head';
import Image from 'next/image';
import { useEffect, useState } from 'react';

import QRCode from "react-qr-code";

import { BsArrowRight, BsPrinterFill } from 'react-icons/bs';
import { useRouter } from 'next/router';

import spliter from '../hooks/spliter';



export default function Home() {

  const router = useRouter();
  const {reference} = router.query;

  const [transaction, setTransaction] = useState({});

  
  useEffect(() => {

    let info = JSON.parse(localStorage.getItem('transactions')).find(t => t.reference === reference);
    setTransaction(info);
    
  }, [reference]);

  return (
    <div>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className="w-full h-screen max-w-md mx-auto p-4">

        <p className='text-center font-bold py-4'>Receipt</p>

        <div className='py-4 space-y-4'>

            {/* <div className='flex justify-between items-center gap-4'>
              <div className='space-y-4'>
                <div className='flex justify-between items-center gap-4'>
                  <div className='relative w-10 h-10 mx-auto'>
                      <Image src={`/img/${transaction?.university?.logo}`} layout="fill" objectFit="cover" />
                  </div>

                  <p className='font-bold '>{transaction?.university?.name}</p>
                </div>

                <p className='text-3xl'>{spliter(reference)}</p>
              </div>

              <div className=''>
                <QRCode 
                  bgColor='#000'
                  fgColor='#fff'
                  size={120}
                  value={reference || "0000000000000"}
                />
              </div>
            </div> */}

            <p className={`${transaction?.type === "credit" ? "text-green-500" : "text-red-500"} font-bold text-4xl text-center`}>&#8358;{Number(transaction?.amount).toLocaleString()}</p>

            <div className='bg-neutral-100 divide-y divide-neutral-200 p-4 rounded-lg'>
                <div className='py-2 space-y-2'>
                    <p className='text-xs text-zinc-700'>Type</p>
                    <p className='text-sm font-bold'>{transaction?.type}</p>
                </div>
                <div className='py-2 space-y-2'>
                    <p className='text-xs text-zinc-700'>Details</p>
                    <p className='text-sm font-bold'>{transaction?.details}</p>
                </div>
                <div className='py-2 space-y-2'>
                    <p className='text-xs text-zinc-700'>Email</p>
                    <p className='text-sm font-bold'>{transaction?.email}</p>
                </div>
                {transaction?.tag && <div className='py-2 space-y-2'>
                    <p className='text-xs text-zinc-700'>To</p>
                    <p className='text-sm font-bold'>{transaction?.tag}</p>
                </div>}
                <div className='py-2 space-y-2'>
                    <p className='text-xs text-zinc-700'>Reference</p>
                    <p className='text-sm font-bold'>{transaction?.reference}</p>
                </div>
            </div>

            <div className=''>
                <p onClick={() => window.print()} className='w-1/2 mx-auto text-white flex items-center justify-center gap-2 p-3 bg-purple-600 rounded-md bg-transparent w-full text-center text-sm font-bold'>
                    Print
                    <BsPrinterFill className='text-white' />
                </p>
            </div>

        </div>

      </main>

    </div>
  )
}
